export const testIds = {
    auth: {
        card: "auth-card",
        title: "auth-title",
        description: "auth-description",
        loginForm: "login-form",
        registerForm: "register-form",
    },
    discover: {
        filterBar: "discover-filter-bar",
        mobileSearchTrigger: "discover-mobile-search-trigger",
        mobileSearchDialog: "discover-mobile-search-dialog",
        mobileNearbyButton: "discover-mobile-nearby-button",
        resultsHeader: "discover-results-header",
        resultsCount: "discover-results-count",
        resultsSummary: "discover-results-summary",
        resultsList: "discover-results-list",
        eventCard: (eventId: string) => `discover-event-card-${eventId}`,
        eventDetailsLink: (eventId: string) => `discover-event-details-link-${eventId}`,
        nearMeUseLocationButton: "near-me-use-location-button",
        nearMeResultButton: (eventId: string) => `near-me-result-button-${eventId}`,
    },
    event: {
        page: "event-page",
        hero: "event-hero",
        aboutSection: "event-about-section",
        meetingPointSection: "event-meeting-point-section",
        discussionSection: "event-discussion-section",
        rsvpCard: "event-rsvp-card",
        rsvpLoginLink: "event-rsvp-login-link",
        hostCard: "event-host-card",
        shellHeader: "event-shell-header",
        shellFooter: "event-shell-footer",
    },
    landing: {
        header: "landing-header",
        mobileMenuTrigger: "landing-mobile-menu-trigger",
        mobileMenu: "landing-mobile-menu",
        mobileMenuInner: "landing-mobile-menu-inner",
        upcomingEventCard: (eventId: string) => `landing-upcoming-event-card-${eventId}`,
    },
} as const
